#!/bin/bash

# cleanup.sh
# Removes all ProvisioningRequests and Jobs generated by the experiment

log() {
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] $1"
}

log "Cleaning up ProvisioningRequest experiment resources..."

# Delete generated YAMLs
rm -f generated-provreq-*.yaml generated-job-*.yaml gen-*.yaml
log "Deleted generated local YAML files."

# Delete ProvisioningRequests
# We look for names starting with prov-req-
REQS=$(kubectl get provreq --no-headers -o custom-columns=":metadata.name" | grep '^prov-req-')

if [[ -n "$REQS" ]]; then
    for REQ in $REQS; do
        log "Deleting ProvisioningRequest: $REQ"
        kubectl delete provreq "$REQ" --wait=false
    done
else
    log "No ProvisioningRequests found to delete."
fi

# Delete Jobs
# We look for names starting with job-
JOBS=$(kubectl get jobs --no-headers -o custom-columns=":metadata.name" | grep '^job-')

if [[ -n "$JOBS" ]]; then
    for JOB in $JOBS; do
        log "Deleting Job: $JOB"
        kubectl delete job "$JOB" --wait=false
    done
else
    log "No Jobs found to delete."
fi
